# 自动标注 Tag
name: Auto Tag

on:
  push:
      branches: [master]
  pull_request:
      branches: [master]
  workflow_dispatch:

jobs:
  update:
    name: Auto Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Get current version
        id: current_version
        run: echo "version=$(cat .github/AutoWriteVersion/version.txt)" >> $GITHUB_OUTPUT
      - name: Check Version
        id: check_version
        run: |
          cd .github/AutoWriteVersion/src/
          deno run --allow-read --allow-write main.ts
      - name: Get new version
        id: new_version
        run: echo "version=$(cat .github/AutoWriteVersion/version.txt)" >> $GITHUB_OUTPUT
      - name: Commit and Set Tag
        if: steps.new_version.outputs.version != steps.current_version.outputs.version
        run: |
          git config --global user.name "Sonic853"
          git config --global user.email "${{ secrets.GH_MAIL }}"
          git add .
          git commit -m "chore(workflow): update version to ${{ steps.new_version.outputs.version }}"
          git tag -a ${{ steps.new_version.outputs.version }} -m "chore(workflow): update version to ${{ steps.new_version.outputs.version }}"
          git push --follow-tags